task:
  - id: stop-all
    variables:
      DCOLL: "ps"
      DCMD: "docker stop $DOCKERID"
      BY_WHAT: "ID"
    next:
      - collect-runs

  # tasks the needs to be done for any running container
  # all of them based on the container id
  #   docker ps --format  '{{json .ID}}'
  - id: collect-runs
    options:
      invisible: true
      displaycmd: true
    require:
      system: linux
      variables:
        DCMD: "*"
        DCOLL: "*"
        BY_WHAT: "*"
    script:      
      - | 
       for DOCKERID in $(docker ${DCOLL} --format  '{{.${BY_WHAT}}}')
       do     
          echo "${DCMD}"  
          ${DCMD}
       done 
